{% set name = "bufrtools" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bufrtools-{{ version }}.tar.gz
  sha256: 9693c9c017554269679d6a6e3022ed3a82b1e347e1eaf3a1872570c299ad7ca5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cftime
    - pandas
    - pocean-core >=1.9.3
    - pyarrow
    - python >=3.6
    - pyyaml

test:
  imports:
    - bufrtools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/axiom-data-science/bufrtools
  summary: A suite of tools for working with BUFR
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/axiom-data-science/bufrtools

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - daf
    - shane-axiom
    - lukecampbell
